### ISSUE TITLE
Found `std.mem.indexOf()` for you.

### ISSUE THREAD

**Issue by p7r0x7** [00JCIV00/cova#36]
```zig
/// Find the Index of a Scalar or Slice `needle` within a Slice `haystack`. (Why is this not in std.mem?!?!? Did I miss it?)
pub fn indexOfEql(comptime T: type, haystack: []const T, needle: T) ?usize {
    switch (@typeInfo(T)) {
        .Pointer => |ptr| {
            for (haystack, 0..) |hay, idx| if (mem.eql(ptr.child, hay, needle)) return idx;
            return null;
        },
        inline else => return mem.indexOfScalar(T, haystack, needle),
    }
}
```

std.mem.indexOf points to std.mem.indexOfPos:
```zig
/// Uses Boyer-Moore-Horspool algorithm on large inputs; `indexOfPosLinear` on small inputs.
pub fn indexOfPos(comptime T: type, haystack: []const T, start_index: usize, needle: []const T) ?usize {
    if (needle.len > haystack.len) return null;
    if (needle.len < 2) {
        if (needle.len == 0) return start_index;
        // indexOfScalarPos is significantly faster than indexOfPosLinear

        return indexOfScalarPos(T, haystack, start_index, needle[0]);
    }

    if (!meta.trait.hasUniqueRepresentation(T) or haystack.len < 52 or needle.len <= 4)
        return indexOfPosLinear(T, haystack, start_index, needle);

    const haystack_bytes = sliceAsBytes(haystack);
    const needle_bytes = sliceAsBytes(needle);

    var skip_table: [256]usize = undefined;
    boyerMooreHorspoolPreprocess(needle_bytes, skip_table[0..]);

    var i: usize = start_index * @sizeOf(T);
    while (i <= haystack_bytes.len - needle_bytes.len) {
        if (i % @sizeOf(T) == 0 and mem.eql(u8, haystack_bytes[i .. i + needle_bytes.len], needle_bytes)) {
            return @divExact(i, @sizeOf(T));
        }
        i += skip_table[haystack_bytes[i + needle_bytes.len - 1]];
    }

    return null;
}
```

**Comment by 00JCIV00** [comment]
Hey, appreciate you looking into this. Unfortunately, that doesn't do exactly what I'm doing in my function. My function allows both scalar and slice Types to be checked against a slice of that same Type. This function (`std.mem.indexOf`) checks for a sub slice within a slice. The other stdlib functions do the same or check a scalar against a slice of that scalar's Type.

**Comment by p7r0x7** [comment]
Scalar isn't a concept I've fully familiarized myself with, evidently.

**Comment by 00JCIV00** [comment]
I've only learned of it in the past few months. Effectively, scalars are the individual Types within the language that all other Types are built from. In Zig this effectively boils down to Integers and Booleans. This is very similar to primitives in some languages but not necessarily the same. All other Types in the language are some kind of grouping of these Types, like Structs, Unions, Enums, Arrays, Slices, etc.

That's just a cursory explanation of course. You can likely find more to it with some digging. (And if you do, please help me learn, haha)

**Comment by p7r0x7** [comment]
I will need to, I'm learning how to implement SIMD optimized functions in spades for this project.
