### ISSUE TITLE
All applicable string comparisons should be probably occur via `ascii.eqlIgnoreCase()`

### ISSUE THREAD

**Issue by p7r0x7** [00JCIV00/cova#37]

**Comment by 00JCIV00** [comment]
While I agree that there may be a few places that this could be applicable, I don't think its good practice to use as the standard. This is particularly true for parsing. Windows is a little lenient on the casing for commands and options, but POSIX systems are not. Those systems treat differently cased strings as different commands or options (or files, or whatever else). For instance `--use` and `--USE` could meant two different things.

All that said, are there certain places you'd like to see case-insensitive equality checks? I definitely wouldn't mind taking a look at some friction points you might be having due to the way checks are being done now.

**Comment by p7r0x7** [comment]
See, in my opinion flags should NEVER be case sensitive--even if values often should be (notably URIs of any kind)--as this adds to end user confusion and makes the command line input less flexible in bizarre situations where this might be out of their control (I can't think of a valid example for this, but being able to use caps anywhere seems beneficial to me).

Regardless, I'll be rewriting all functions pertaining to the behavior and printing of my CLI for my apps, as you've so graciously made available, so your decision here doesn't especially affect me. I recommend giving https://clig.dev/ a read if you haven't already (though you probably have). I haven't read it all myself and don't agree with everything necessarily, but it seems to have loads of interesting ideas pertaining to this.

**Comment by 00JCIV00** [comment]
That's fully understandable. Thankfully the callback functions help meet that need as you've seen (and tested thoroughly in a way that I'm very appreciative of).

I've actually never read or seen that site! When I initially started Cova, I decided to do it naively in a way that just made sense to me to see how it would turn out. I think I've reached a point where reading through something like that could be very beneficial though, so thank you! You may see some features referencing that site after the v0.9.0 release.

**Comment by 00JCIV00** [comment]
I'm partial to A in this case. That's both a reasonable and fairly simple change to make.

It also fits in well with some changes I'm considering based on our conversations through a few issues. As a heads up to you, I'm likely going to do the following for fields that can be set via both a Config Struct and directly on an instance of an Argument Type:

1. No prefix: This is reserved for fields set directly on the instance of an Argument Type.
2. `child_type_` prefix: This will be for fields in a Config Struct that are set based on a specific Child Type (Options and Values only). 
3. `global_` prefix: This will be for fields in a Config Struct that are set for ALL instances of the corresponding Argument Type. Think of it as changing the default behavior for that Argument Type. 

When being processed the order of precedence will be as listed above ending in the default behavior of Cova. 

The intent here is to make the usage of these fields a bit more clear without needing to refer to the Docs as often. More to follow on that.

**Comment by p7r0x7** [comment]
No objections here! And I appreciate the heads up.

**Comment by 00JCIV00** [comment]
Closed w/ 2aa9c74.
