### ISSUE TITLE
Reconsider usage of `inline` within Cova.

### ISSUE THREAD

**Issue by p7r0x7** [00JCIV00/cova#38]
https://ziggit.dev/t/inlining-functions/1341/3:
<img width="787" alt="Screenshot 2023-10-26 at 1 37 07 AM" src="https://github.com/00JCIV00/cova/assets/54943589/73215f4e-abe2-4189-bf90-a2b0727254f6">

**Comment by 00JCIV00** [comment]
To my knowledge, I'm not using `inline fn` functions anywhere (though please feel free to point out an example if I'm mistaken.)

What you may be referring to is my use of `inline for` loops. While these concepts are closely related, they're not the same. My use of `inline for` is required to loop over certain datasets, especially those dealing with Type metadata. To my knowledge, the feeling towards using `inline for` is almost the opposite to that of `inline fn`. It's often encouraged, or at the very least not discouraged.

**Comment by p7r0x7** [comment]
This was a distinction I was not aware of, and I'm glad to see this too was well thought through! I'll close this and trust that further uses of `inline` will be decided carefully as well.
