### ISSUE TITLE
Support for sub commands and options to be hidden from global help/usage (via omission).

### ISSUE THREAD

**Issue by p7r0x7** [00JCIV00/cova#45]
All that would be required for this would be a non-optional boolean field in each option and command. Mandatory values have no need for this. (The default printing functions need to respond to this field accordingly, as well).

This was mentioned because it's a very common feature in libraries such as this with many valid use cases.

**Comment by 00JCIV00** [comment]
Good call and an easy feature to implement. See [54d7dfb](https://github.com/00JCIV00/cova/commit/54d7dfb23c73d041e71a8b42676ead6a830cd044) for details.
