### ISSUE TITLE
Printing callbacks should return a usize that end users can flexibly configure to mean anything they want.

### ISSUE THREAD

**Issue by p7r0x7** [00JCIV00/cova#50]
The suggested behavior is similar to how the current Zig writer syntax already works, but given the context of a CLI, the value returned usize value can mean anything. This would greatly improve users' ability to control how the CLI prints itself based on the meaning of that calculated runtime value.

**Comment by p7r0x7** [comment]
I personally will set that value to the count of runtime-printed runes of visible characters.

**Comment by 00JCIV00** [comment]
I think we resolved this a while back. If not, we can take another look following the v0.10 release.
