### ISSUE TITLE
Default help doesn't adapt to cova.Command.Custom.FromConfig setting

### ISSUE THREAD

**Issue by AdjectiveAllison** [00JCIV00/cova#53]
I set `.attempt_short_opts = false,` when converting from a struct with `cova.Command.Custom.from()`. The resulting help output shows -null as the short option instead of excluding it from the help output. This happens on both 0.9.1 and current main branch. See here:

```shell
        Temperature:
            -null,--temperature <temperature (f16)>
            The 'temperature' Option of type '?f16'.
```

I did just realize that -u and -h are set to enabled by default, maybe the fact that they have short options but the others don't is where the formatting goes wrong?

**Comment by 00JCIV00** [comment]
@AdjectiveAllison Appreciate you pointing this out. I remember tackling this previously, so I must've had a regression. I'll look into it this week and squash it properly.

**Comment by 00JCIV00** [comment]
0d38429a094053d78a69e1fe32e5f47d78c24766

Additional fixes that should solve this issue more effectively.
