### ISSUE TITLE
Options with "empty" values are not allowed

### ISSUE THREAD

**Issue by charlesrocket** [00JCIV00/cova#64]
Could not implement custom multi-value without breaking changes https://github.com/charlesrocket/xtxf/commit/660b9462f5083b1a69f00e0914ca219ae049efb7.

Currently, there is no way to allow `-f` while `-f=a,b` is valid.

**Comment by 00JCIV00** [comment]
@charlesrocket I got around to implementing this. In order to use it, be sure to set the `allow_empty` field on your desired Options and check for `opt.val.isEmpty()` when analyzing the parsed Arguments.
